### ISSUE TITLE
Docs search does not search all content

### ISSUE THREAD

**Issue by fnesveda** [apify/apify-docs#1109]
When searching for content in the [Python SDK docs](https://docs.apify.com/sdk/python/reference), the search returns results only from the JS libraries:

![Screenshot 2024-07-23 at 1 11 20](https://github.com/user-attachments/assets/d518ecf6-7aa8-4336-aca6-5f09758cb824)

**Comment by barjin** [comment]
This is likely because of a tie in ranking between the JS and Python results in Algolia.

Since the modal reranks [only the top 25 Algolia results](https://github.com/apify/docs-search-modal/blob/master/src/components/ApifySearch.tsx#L86-L112), we're probably hitting the classic issue of two-stage retrieval (the first stage does not yield the desired results). 

The proper way of solving this would probably be splitting the search into two disjoint faceted searches on the `section` attribute (i.e. first search only in the current section, then in all the rest and combine the results). This might diminish the serendipity of the search, though (likely not such an issue in our case).
