### ISSUE TITLE
Embed YouTube videos

### ISSUE THREAD

**Issue by honzajavorek** [apify/apify-docs#964]
The page on [Anti-scraping protections](https://docs.apify.com/academy/anti-scraping) mentions a talk by @mnmkng:

> For an in-depth video explanation of anti-scraping, and how to fix issues caused by it, check out [this talk](https://www.youtube.com/watch?v=aXil0K-M-Vs) from [Ondra Urban](https://github.com/mnmkng).

Can we embed it instead of linking it? I'm filing this issue to discuss whether we want to do this and how can we do this with Markdown and Docusaurus. The video mentioned above is an obvious case, which could be taken as a first instance where to implement the approach.

I like multi-modal tutorials. The Academy is already quite awesome in not being afraid to use images. Together with the fact that Apify's YouTube channel gets new content almost every week now, let's add videos! 📺 

One challenge could be YouTube's tracking cookies. Their embeds track visitors, so they shouldn't automatically load for people with [DNT](https://en.wikipedia.org/wiki/Do_Not_Track) set, etc. We'd need to add cookie consent. One solution is to insert an image which looks like YouTube player, but in fact just links to the video and opens it in a new tab. Preparing such images is more work though.

**Comment by mnmkng** [comment]
Yes please. We should. AFAIK historically Docusaurus did not support embedding videos out of the box, but it must've changed by now.

In the future, I would like most of the content on the Academy to have a video version as well.

I'm not sure if we need a cookie consent specifically for YouTube embedding, because technically we're not the ones setting or manipulating the cookies. My hunch is that we don't, but I'd have to look it up.

In any case, we can do some quick improvements by using [a guide like this](https://ardalis.com/how-to-embed-youtube-video-in-github-readme-markdown/) to link to the videos while reusing their existing thumbnails.

**Comment by honzajavorek** [comment]
<img width="281" alt="Screenshot 2024-05-20 at 11 18 22" src="https://github.com/apify/apify-docs/assets/283441/727a592c-63d6-4cf2-8acb-5c55b3374e85">

The page you provided as an example uses the `https://www.youtube-nocookie.com` domain. Nice! That probably settles all concerns in that regard 😀

![image](https://github.com/apify/apify-docs/assets/283441/cfe51f26-69b9-49d1-93a3-eed5ea5321a0)
